site_name: Otus SRE Homeworks
site_url: https://somikhailov.github.io/otus-sre

nav:
   - Home: index.md
   - Домашние задания: hw.md
   - Создание диаграммы с помощью Diagrams: diagrams.md
   - SLI/SLO и риски: sli_slo_risks.md
theme: readthedocs
