---
# tasks file for ansible/roles/docker
- name: create dicrectory flask-crud
  file:
    path: /flask-crud
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy docker-compose
  template:
    src: docker-compose.yml.j2
    dest: /flask-crud/docker-compose.yml
    owner: root
    group: root
    mode: 0775

- name: start docker-compose
  docker_compose:
    project_src: /flask-crud