- name: add apt_key docker repo
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: add docker repo
  apt_repository:
    repo: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker.list

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - docker-ce
    - docker-compose
    - python3-pip

- name: Install pip packages
  pip:
    name: "{{ item }}"
  loop:
    - docker >= 1.20