---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: "Include flask_crud vars"
    include_vars: ../../defaults/main.yml

  - name: Variable assertion
    assert:
      that: 
        - image is defined
        - version is defined
        
  - name: Confirm that 200 OK response is returned
    uri:
      url: "http://{{ ansible_host }}"
      status_code: 200
